import Head from 'next/head'
import Main from '@/scenes/Main'
import Customizer from '@/scenes/Customizer'
import Canvas from '@/canvas'

export default function Home() {
  return (
    <>
      <Head>
        <title>3D Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className='app transition-all ease-in'>
        <Main />
        <Canvas />
        <Customizer />
      </main>
    </>
  )
}
